version: '3.8'
services:
  app:
    image: minjipk/eyeson:latest
    ports:
      - "8000:8000"
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    restart: unless-stopped
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    restart: unless-stopped