# aws.yml
name: main branch auto ci process script

on: # 아래 job을 실행시킬 상황
  push:
    branches: [ main ]

jobs:
  deploy:
    name: deploy
    runs-on: ubuntu-latest # 실행될 인스턴스 OS와 버전

    steps:
      - name: ssh to ec2
        uses: appleboy/ssh-action@master # ssh 접속하는 오픈소스
        with:
          host: ${{ secrets.REMOTE_IP }} # 인스턴스 IP
          username: ${{ secrets.REMOTE_USER }} # 우분투 아이디
          key: ${{ secrets.REMOTE_PRIVATE_KEY }} # ec2 instance pem key
          script: | # 실행할 스크립트
            cd eyeson/backend
            ls
            conda activate eyeson
            conda info --envs
            git pull
            sudo fuser -k 8000/tcp
            nohup $(which uvicorn) main:app --host 0.0.0.0 --port 8000 --reload
