# aws.yml
name: main branch auto ci process script

on: # 아래 job을 실행시킬 상황
  push:
    branches: [ main ]

jobs:
  deploy:
    name: deploy
    runs-on: ubuntu-latest # 실행될 인스턴스 OS와 버전
    defaults:
      run:
        shell: bash -l {0}

    steps:
      # 1. 코드 체크아웃
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. EC2에 배포
      - name: Deploy to EC2
        uses: appleboy/ssh-action@master # ssh 접속하는 오픈소스
        with:
          host: ${{ secrets.REMOTE_IP }} # 인스턴스 IP
          username: ${{ secrets.REMOTE_USER }} # 우분투 아이디
          key: ${{ secrets.REMOTE_PRIVATE_KEY }} # ec2 instance pem key
          script: | # 실행할 스크립트
            cd eyeson/backend
            git pull
            
            # FastAPI 서비스 재시작
            sudo systemctl restart fastapi
            sleep 3  # 서비스 재시작 후 대기

            # FastAPI 상태 확인
            if ! curl -s http://localhost:8000/docs > /dev/null; then
              echo "Failed to restart FastAPI service. Check logs:"
              sudo journalctl -u fastapi.service -n 20
              exit 1
            fi

            # Nginx 설정 점검 및 재시작
            sudo nginx -t
            if [ $? -eq 0 ]; then
              sudo systemctl restart nginx
              echo "Nginx restarted successfully"
            else
              echo "Nginx configuration test failed"
              exit 1
            fi